export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

// Action types for confirmed order
export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST';
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS';
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE';

// Action types for placed order
export const PLACED_ORDER_REQUEST = 'PLACED_ORDER_REQUEST';
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDER_SUCCESS';
export const PLACED_ORDER_FAILURE = 'PLACED_ORDER_FAILURE';

// actionTypes.js for shipped order
export const SHIP_ORDER_REQUEST = 'SHIP_ORDER_REQUEST';
export const SHIP_ORDER_SUCCESS = 'SHIP_ORDER_SUCCESS';
export const SHIP_ORDER_FAILURE = 'SHIP_ORDER_FAILURE';